START TRANSACTION;

ALTER TABLE app_user
  ADD COLUMN
  legacyId VARCHAR(50);

ALTER TABLE competition
  ADD COLUMN
  legacyId VARCHAR(50);

ALTER TABLE league
  ADD COLUMN
  legacyId VARCHAR(50);

ALTER TABLE team
  ADD COLUMN
  legacyId VARCHAR(50);

ALTER TABLE game_match
  ADD COLUMN
  legacyId VARCHAR(50);

ALTER TABLE game_map
  ADD CONSTRAINT UC_MAP_NAME UNIQUE (name);

ALTER TABLE app_user
  ADD CONSTRAINT UC_LEGACYID UNIQUE (legacyId);

ALTER TABLE competition
  ADD CONSTRAINT UC_LEGACYID UNIQUE (legacyId);

ALTER TABLE league
  ADD CONSTRAINT UC_LEGACYID UNIQUE (legacyId);

ALTER TABLE team
  ADD CONSTRAINT UC_LEGACYID UNIQUE (legacyId);

ALTER TABLE game_match
  ADD CONSTRAINT UC_LEGACYID UNIQUE (legacyId);

COMMIT;